/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package spaced_repetition.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Message extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6759421588333548542L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Message\",\"namespace\":\"spaced_repetition.avro\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"question\",\"type\":\"string\"},{\"name\":\"correctAnswers\",\"type\":\"int\",\"default\":0},{\"name\":\"answer\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<Message> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Message> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Message> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Message> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Message> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Message to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Message from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Message instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Message fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID id;
  private java.lang.CharSequence question;
  private int correctAnswers;
  private java.lang.CharSequence answer;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Message() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param question The new value for question
   * @param correctAnswers The new value for correctAnswers
   * @param answer The new value for answer
   */
  public Message(java.util.UUID id, java.lang.CharSequence question, java.lang.Integer correctAnswers, java.lang.CharSequence answer) {
    this.id = id;
    this.question = question;
    this.correctAnswers = correctAnswers;
    this.answer = answer;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return question;
    case 2: return correctAnswers;
    case 3: return answer;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.util.UUID)value$; break;
    case 1: question = (java.lang.CharSequence)value$; break;
    case 2: correctAnswers = (java.lang.Integer)value$; break;
    case 3: answer = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.util.UUID getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.util.UUID value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'question' field.
   * @return The value of the 'question' field.
   */
  public java.lang.CharSequence getQuestion() {
    return question;
  }


  /**
   * Sets the value of the 'question' field.
   * @param value the value to set.
   */
  public void setQuestion(java.lang.CharSequence value) {
    this.question = value;
  }

  /**
   * Gets the value of the 'correctAnswers' field.
   * @return The value of the 'correctAnswers' field.
   */
  public int getCorrectAnswers() {
    return correctAnswers;
  }


  /**
   * Sets the value of the 'correctAnswers' field.
   * @param value the value to set.
   */
  public void setCorrectAnswers(int value) {
    this.correctAnswers = value;
  }

  /**
   * Gets the value of the 'answer' field.
   * @return The value of the 'answer' field.
   */
  public java.lang.CharSequence getAnswer() {
    return answer;
  }


  /**
   * Sets the value of the 'answer' field.
   * @param value the value to set.
   */
  public void setAnswer(java.lang.CharSequence value) {
    this.answer = value;
  }

  /**
   * Creates a new Message RecordBuilder.
   * @return A new Message RecordBuilder
   */
  public static spaced_repetition.avro.Message.Builder newBuilder() {
    return new spaced_repetition.avro.Message.Builder();
  }

  /**
   * Creates a new Message RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Message RecordBuilder
   */
  public static spaced_repetition.avro.Message.Builder newBuilder(spaced_repetition.avro.Message.Builder other) {
    if (other == null) {
      return new spaced_repetition.avro.Message.Builder();
    } else {
      return new spaced_repetition.avro.Message.Builder(other);
    }
  }

  /**
   * Creates a new Message RecordBuilder by copying an existing Message instance.
   * @param other The existing instance to copy.
   * @return A new Message RecordBuilder
   */
  public static spaced_repetition.avro.Message.Builder newBuilder(spaced_repetition.avro.Message other) {
    if (other == null) {
      return new spaced_repetition.avro.Message.Builder();
    } else {
      return new spaced_repetition.avro.Message.Builder(other);
    }
  }

  /**
   * RecordBuilder for Message instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Message>
    implements org.apache.avro.data.RecordBuilder<Message> {

    private java.util.UUID id;
    private java.lang.CharSequence question;
    private int correctAnswers;
    private java.lang.CharSequence answer;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(spaced_repetition.avro.Message.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.question)) {
        this.question = data().deepCopy(fields()[1].schema(), other.question);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.correctAnswers)) {
        this.correctAnswers = data().deepCopy(fields()[2].schema(), other.correctAnswers);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.answer)) {
        this.answer = data().deepCopy(fields()[3].schema(), other.answer);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Message instance
     * @param other The existing instance to copy.
     */
    private Builder(spaced_repetition.avro.Message other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.question)) {
        this.question = data().deepCopy(fields()[1].schema(), other.question);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.correctAnswers)) {
        this.correctAnswers = data().deepCopy(fields()[2].schema(), other.correctAnswers);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.answer)) {
        this.answer = data().deepCopy(fields()[3].schema(), other.answer);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.util.UUID getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public spaced_repetition.avro.Message.Builder setId(java.util.UUID value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public spaced_repetition.avro.Message.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'question' field.
      * @return The value.
      */
    public java.lang.CharSequence getQuestion() {
      return question;
    }


    /**
      * Sets the value of the 'question' field.
      * @param value The value of 'question'.
      * @return This builder.
      */
    public spaced_repetition.avro.Message.Builder setQuestion(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.question = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'question' field has been set.
      * @return True if the 'question' field has been set, false otherwise.
      */
    public boolean hasQuestion() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'question' field.
      * @return This builder.
      */
    public spaced_repetition.avro.Message.Builder clearQuestion() {
      question = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'correctAnswers' field.
      * @return The value.
      */
    public int getCorrectAnswers() {
      return correctAnswers;
    }


    /**
      * Sets the value of the 'correctAnswers' field.
      * @param value The value of 'correctAnswers'.
      * @return This builder.
      */
    public spaced_repetition.avro.Message.Builder setCorrectAnswers(int value) {
      validate(fields()[2], value);
      this.correctAnswers = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'correctAnswers' field has been set.
      * @return True if the 'correctAnswers' field has been set, false otherwise.
      */
    public boolean hasCorrectAnswers() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'correctAnswers' field.
      * @return This builder.
      */
    public spaced_repetition.avro.Message.Builder clearCorrectAnswers() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'answer' field.
      * @return The value.
      */
    public java.lang.CharSequence getAnswer() {
      return answer;
    }


    /**
      * Sets the value of the 'answer' field.
      * @param value The value of 'answer'.
      * @return This builder.
      */
    public spaced_repetition.avro.Message.Builder setAnswer(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.answer = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'answer' field has been set.
      * @return True if the 'answer' field has been set, false otherwise.
      */
    public boolean hasAnswer() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'answer' field.
      * @return This builder.
      */
    public spaced_repetition.avro.Message.Builder clearAnswer() {
      answer = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Message build() {
      try {
        Message record = new Message();
        record.id = fieldSetFlags()[0] ? this.id : (java.util.UUID) defaultValue(fields()[0]);
        record.question = fieldSetFlags()[1] ? this.question : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.correctAnswers = fieldSetFlags()[2] ? this.correctAnswers : (java.lang.Integer) defaultValue(fields()[2]);
        record.answer = fieldSetFlags()[3] ? this.answer : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Message>
    WRITER$ = (org.apache.avro.io.DatumWriter<Message>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Message>
    READER$ = (org.apache.avro.io.DatumReader<Message>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










